apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  # type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080